export const developers = [
  {
    id: 1,
    name: "Isaac Abu",
    role: "Lead Frontend Engineer",
    skills: ["React", "Tailwind", "TypeScript", "Redux"],
    bio: "Isaac leads UI/UX-focused frontend development and creates accessible, high-performance apps.",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=placeholder",
    linkedin: "#",
    github: "#",
    phone: "+233 24 123 4567",
  },
  {
    id: 2,
    name: "Jamal Abdul Nasir",
    role: "Frontend Engineer",
    skills: ["React", "Tailwind", "TypeScript", "Redux"],
    bio: "Jamal works on UI/UX-focused frontend development and creates accessible, high-performance apps.",
    img: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=placeholder",
    linkedin: "https://www.linkedin.com/in/jamalabdulnasir/",
    github: "https://github.com/jamalabdulnasir220?tab=repositories",
    phone: "+233 54 657 3849",
  },
  // {
  //   id: 3,
  //   name: "Enam",
  //   role: "Frontend Engineer",
  //   skills: ["Next.js", "React", "Prisma"],
  //   bio: "Enam ships end-to-end features and bridges design with engineering.",
  //   img: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=placeholder",
  //   linkedin: "#",
  //   github: "#",
  // },
];
